name: Build PostgreSQL Client Binaries

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
permissions:
  contents: write   # 🔹 necesario para crear releases
jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: debian:stretch
    strategy:
      matrix:
        version: [16.3-1]
    steps:
      - name: Build on Debian Stretch        
        run: |
          MAJOR=$(echo "${{ matrix.version }}" | cut -d. -f1)
          echo "deb http://apt.postgresql.org/pub/repos/apt stretch-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
          apt-get update
          apt-get download postgresql-client-$MAJOR
          dpkg -x postgresql-client-$MAJOR*.deb ./pg$MAJOR-linux
          apt-get download libpq5
          dpkg -x libpq5*.deb ./pg$MAJOR-linux
          ls -R ./pg$MAJOR-linux
          tar -czf pg-bin${{ matrix.version }}-linux.tar.gz -C . pg$MAJOR-linux
          
      - name: Upload artifact (Linux)        
        uses: actions/upload-artifact@v4
        with:
          name: pg-bin${{ matrix.version }}-linux.tar.gz
          path: .
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [10.23-1, 12.22-1, 16.3-1]
    steps:
      - name: Download PostgreSQL client 16 (Windows binaries)        
        run: |
          curl -L -o pg${{ matrix.version }}-win.zip https://get.enterprisedb.com/postgresql/postgresql-${{ matrix.version }}-windows-x64-binaries.zip
          mkdir pg${{ matrix.version }}-win
          unzip pg${{ matrix.version }}-win.zip "pgsql/bin/*" -d pg${{ matrix.version }}-win
          # Empaquetar solo la carpeta bin
          tar -czf pg-bin${{ matrix.version }}-win.tar.gz -C pg${{ matrix.version }}-win/pgsql bin
          
      - name: Upload artifact (windows)        
        uses: actions/upload-artifact@v4
        with:
          name: pg-bin${{ matrix.version }}-win.tar.gz
          path: .

  release:
    needs: [build-linux,build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          path: ./dists
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dists/pg-bin*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
