name: Build PostgreSQL Client Binaries

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
permissions:
  contents: write   # 🔹 necesario para crear releases
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [10.23-1, 12.22-1, 16.3-1]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          MAJOR=$(echo "${{ matrix.version }}" | cut -d. -f1)
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt noble-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          apt-get download postgresql-client-$MAJOR
          dpkg -x postgresql-client-$MAJOR*.deb ./pg$MAJOR-linux
          apt-get download libpq5
          dpkg -x libpq5*.deb ./pg$MAJOR-linux
          ls -R ./pg$MAJOR-linux
          tar -czf pg$MAJOR-linux-clean.tar.gz -C . pg$MAJOR-linux
          
      - name: Upload artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: pg${{ matrix.version }}-linux.tar.gz
          path: .

      - name: Download PostgreSQL client 16 (Windows binaries)
        if: matrix.os == 'windows-latest'
        run: |
          curl -L -o pg${{ matrix.version }}-win.zip https://get.enterprisedb.com/postgresql/postgresql-${{ matrix.version }}-windows-x64-binaries.zip
          mkdir pg${{ matrix.version }}-win
          unzip pg${{ matrix.version }}-win.zip "pgsql/bin/*" -d pg${{ matrix.version }}-win
          # Empaquetar solo la carpeta bin
          tar -czf pg${{ matrix.version }}-win-bin.tar.gz -C pg${{ matrix.version }}-win/pgsql bin
          
      - name: Upload artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: pg${{ matrix.version }}-win-bin.tar.gz
          path: .

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          path: ./dists
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dists/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
