name: Build PostgreSQL Client Binaries

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
permissions:
  contents: write   # 🔹 necesario para crear releases
jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: debian:stretch
    strategy:
      matrix:
        version: [16.3]
    steps:
      - name: Build on Debian Stretch

        run: |
          MAJOR=$(echo "${{ matrix.version }}" | cut -d. -f1)
          echo "deb http://archive.debian.org/debian stretch main contrib non-free" > /etc/apt/sources.list
          echo "deb http://archive.debian.org/debian-security stretch/updates main contrib non-free" >> /etc/apt/sources.list
          apt-get -o Acquire::Check-Valid-Until=false update
         
          apt-get install -y build-essential wget curl libreadline-dev zlib1g-dev flex bison libicu-dev
          wget https://ftp.postgresql.org/pub/source/v${{ matrix.version }}/postgresql-${{ matrix.version }}.tar.gz
          tar -xzf postgresql-${{ matrix.version }}.tar.gz
          cd postgresql-${{ matrix.version }}
          ./configure --prefix=/pg${{ matrix.version }}-linux --without-icu
          make -j$(nproc)
          make install
          cd ..
          tar -czf pg-bin${{ matrix.version }}-linux.tar.gz -C / pg${{ matrix.version }}-linux
          mv pg-bin${{ matrix.version }}-linux.tar.gz $GITHUB_WORKSPACE/pg-bin-release-${{ matrix.version }}-linux.tar.gz
          

      - name: Cache artifact
        uses: actions/cache@v2
        with:
          path: pg-bin-release-${{ matrix.version }}-linux.tar.gz
          key: pg-bin-release-16.3-linux    
  upload-linux:
    needs: build-linux
    runs-on: ubuntu-latest
    steps:
      - name: Restore artifact from cache
        uses: actions/cache@v4
        with:
          path: pg-bin-release-16.3-linux.tar.gz
          key: pg-bin-release-16.3-linux

      - name: List files
        run: ls -lh
      - name: Upload artifact (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: pg-bin-release-16.3-linux.tar.gz
          path: pg-bin-release-16.3-linux.tar.gz        
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [10.23-1, 12.22-1, 16.3-1]
    steps:
      - name: Download PostgreSQL client 16 (Windows binaries)        
        run: |
          curl -L -o pg${{ matrix.version }}-win.zip https://get.enterprisedb.com/postgresql/postgresql-${{ matrix.version }}-windows-x64-binaries.zip
          mkdir pg${{ matrix.version }}-win
          unzip pg${{ matrix.version }}-win.zip "pgsql/bin/*" -d pg${{ matrix.version }}-win
          # Empaquetar solo la carpeta bin
          tar -czf pg-bin${{ matrix.version }}-win.tar.gz -C pg${{ matrix.version }}-win/pgsql bin
          
      - name: Upload artifact (windows)        
        uses: actions/upload-artifact@v4
        with:
          name: pg-bin${{ matrix.version }}-win.tar.gz
          path: .

  release:
    needs: [build-linux,build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          path: ./dists
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dists/pg-bin*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
